bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "rules_jvm_external", version = "6.9")
bazel_dep(name = "rules_android", version = "0.6.6")
bazel_dep(name = "rules_java", version = "8.9.0")

remote_android_extensions = use_extension(
    "@rules_android//bzlmod_extensions:android_extensions.bzl",
    "remote_android_tools_extensions",
)
use_repo(remote_android_extensions, "android_tools")

android_sdk_repository_extension = use_extension("@rules_android//rules/android_sdk_repository:rule.bzl", "android_sdk_repository_extension")
use_repo(android_sdk_repository_extension, "androidsdk")

register_toolchains("@androidsdk//:sdk-toolchain", "@androidsdk//:all")

# maven
maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        # compose
#         "org.jetbrains.compose.ui:ui:1.9.3",
#         "org.jetbrains.compose.material3:material3:1.9.3",
#         "org.jetbrains.compose.runtime:runtime:1.9.3",
        "org.jetbrains.kotlinx:kotlinx-serialization-json-okio:1.8.1",
        # kodein di
        "org.kodein.di:kodein-di-jvm:7.26.1",

        # logging
        "io.github.microutils:kotlin-logging-jvm:3.0.5",
        # kotlinx cli
        "org.jetbrains.kotlinx:kotlinx-cli-jvm:0.3.6",
        # okio
        "com.squareup.okio:okio:3.16.0",
        # room
        "androidx.room:room-runtime:2.8.4",
        "androidx.room:room-compiler:2.8.4",  # Required for the processor
        "androidx.room:room-common:2.8.4",
        # bignum
        "com.ionspin.kotlin:bignum-jvm:0.3.10",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
use_repo(maven, "maven")

# kotlin
bazel_dep(name = "rules_kotlin", version = "2.2.2")

register_toolchains("//:kotlin_toolchain")

bazel_dep(name = "linuxcnc_proto")
local_path_override(module_name = "linuxcnc_proto", path="/home/dragos/IdeaProjects/linuxcnc-proto")