load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "args",
    srcs = [
        "ArgProcessor.kt",
        "DarkMode.kt",
        "LinuxCncHome.jvm.kt",
        "StartupArgs.kt"
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_squareup_okio_okio_jvm",
        "@maven//:org_jetbrains_kotlinx_kotlinx_cli_jvm",
        "@maven//:io_github_microutils_kotlin_logging_jvm",
#         "@maven//:org_jetbrains_compose_ui_ui"
    ]
)